/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'userId' : Principal,
  'text' : string,
  'timestamp' : Time,
  'questionId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Option { 'text' : string, 'image' : [] | [ExternalBlob] }
export interface Question {
  'id' : bigint,
  'subject' : string,
  'difficulty' : string,
  'explanation' : [] | [string],
  'createdAt' : Time,
  'createdBy' : Principal,
  'correctAnswer' : bigint,
  'questionText' : string,
  'updatedAt' : [] | [Time],
  'classLevel' : TestType,
  'image' : [] | [ExternalBlob],
  'chapter' : string,
  'options' : Array<Option>,
}
export type SectionType = { 'full' : null } |
  { 'physicsChemistry' : null } |
  { 'mathematics' : null };
export interface Suggestion {
  'id' : bigint,
  'feedback' : string,
  'author' : string,
  'timestamp' : Time,
}
export interface SuggestionsResponse {
  'suggestions' : Array<Suggestion>,
  'count' : bigint,
}
export interface TestAttempt {
  'userId' : Principal,
  'answers' : Array<bigint>,
  'submittedAt' : Time,
  'score' : bigint,
  'timeTaken' : bigint,
  'testId' : bigint,
}
export interface TestConfig {
  'id' : bigint,
  'startTime' : [] | [Time],
  'isPublished' : boolean,
  'subject' : string,
  'endTime' : [] | [Time],
  'sectionType' : [] | [SectionType],
  'isStopped' : boolean,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'testType' : TestType,
  'updatedAt' : [] | [Time],
  'totalQuestions' : bigint,
  'durationMinutes' : bigint,
  'chapters' : Array<string>,
  'markingScheme' : {
    'incorrectPenalty' : bigint,
    'correctMarks' : bigint,
    'penaltyOption' : [] | [string],
  },
  'questions' : Array<bigint>,
}
export type TestStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'ended' : null } |
  { 'finished' : null };
export type TestType = { 'class11' : null } |
  { 'class12' : null } |
  { 'completeSyllabus' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'isBlocked' : boolean,
  'createdAt' : Time,
  'youtubeVerificationTimestamp' : [] | [Time],
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'isYouTubeVerified' : boolean,
  'lastLogin' : Time,
  'testAttempts' : Array<TestAttempt>,
  'blockTimestamp' : [] | [Time],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachOptionImage' : ActorMethod<[bigint, bigint, ExternalBlob], undefined>,
  'attachQuestionImage' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'createQuestion' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<Option>,
      bigint,
      [] | [string],
      [] | [ExternalBlob],
      TestType,
    ],
    bigint
  >,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteExpiredUnpublishedTests' : ActorMethod<[], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'deleteSuggestion' : ActorMethod<[bigint], undefined>,
  'getAllTestConfigsWithStatus' : ActorMethod<
    [],
    Array<[TestConfig, TestStatus]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentlyLiveTestsWithStatus' : ActorMethod<
    [],
    Array<[TestConfig, TestStatus]>
  >,
  'getQuestion' : ActorMethod<[bigint], [] | [Question]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCommentsForQuestion' : ActorMethod<[bigint], Array<Comment>>,
  'listQuestions' : ActorMethod<[[] | [string]], Array<Question>>,
  'listQuestionsBySubject' : ActorMethod<[string], Array<Question>>,
  'listSuggestions' : ActorMethod<[], SuggestionsResponse>,
  'postComment' : ActorMethod<[bigint, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], UserProfile>,
  'setYouTubeVerified' : ActorMethod<[], undefined>,
  'submitSuggestion' : ActorMethod<[string, string], bigint>,
  'updateQuestion' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Array<Option>,
      bigint,
      [] | [string],
      [] | [ExternalBlob],
      TestType,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];