/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Option = IDL.Record({
  'text' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const TestType = IDL.Variant({
  'class11' : IDL.Null,
  'class12' : IDL.Null,
  'completeSyllabus' : IDL.Null,
});
export const Time = IDL.Int;
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'updatedAt' : IDL.Opt(Time),
  'classLevel' : TestType,
  'image' : IDL.Opt(ExternalBlob),
  'chapter' : IDL.Text,
  'options' : IDL.Vec(Option),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SectionType = IDL.Variant({
  'full' : IDL.Null,
  'physicsChemistry' : IDL.Null,
  'mathematics' : IDL.Null,
});
export const GalleryQuestionPreview = IDL.Record({
  'id' : IDL.Nat,
  'previewImage' : IDL.Opt(ExternalBlob),
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'hasImage' : IDL.Bool,
  'snippet' : IDL.Text,
  'questionText' : IDL.Text,
  'chapter' : IDL.Text,
  'options' : IDL.Vec(Option),
});
export const TestAttempt = IDL.Record({
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'submittedAt' : Time,
  'score' : IDL.Float64,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'createdAt' : Time,
  'youtubeVerificationTimestamp' : IDL.Opt(Time),
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'isYouTubeVerified' : IDL.Bool,
  'lastLogin' : Time,
  'testAttempts' : IDL.Vec(TestAttempt),
  'blockTimestamp' : IDL.Opt(Time),
});
export const TestConfig = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Opt(Time),
  'isPublished' : IDL.Bool,
  'subject' : IDL.Text,
  'endTime' : IDL.Opt(Time),
  'sectionType' : IDL.Opt(SectionType),
  'isStopped' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'testType' : TestType,
  'updatedAt' : IDL.Opt(Time),
  'totalQuestions' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'chapters' : IDL.Vec(IDL.Text),
  'markingScheme' : IDL.Record({
    'incorrectPenalty' : IDL.Float64,
    'correctMarks' : IDL.Float64,
  }),
  'questions' : IDL.Vec(IDL.Nat),
});
export const ActiveSession = IDL.Record({
  'startTime' : Time,
  'userId' : IDL.Principal,
  'lastActivity' : Time,
  'testId' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'text' : IDL.Text,
  'timestamp' : Time,
  'questionId' : IDL.Nat,
});
export const Suggestion = IDL.Record({
  'id' : IDL.Nat,
  'feedback' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const SuggestionsResponse = IDL.Record({
  'suggestions' : IDL.Vec(Suggestion),
  'count' : IDL.Nat,
});
export const TestStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'ended' : IDL.Null,
  'finished' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'rank' : IDL.Nat,
  'submittedAt' : Time,
  'score' : IDL.Float64,
  'userProfile' : UserProfile,
});
export const OverallLeaderboardEntry = IDL.Record({
  'rank' : IDL.Nat,
  'totalAttempts' : IDL.Nat,
  'userProfile' : UserProfile,
  'averageScore' : IDL.Float64,
});
export const SanitizedQuestion = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'questionText' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'chapter' : IDL.Text,
  'options' : IDL.Vec(Option),
});
export const SystemMetrics = IDL.Record({
  'totalTests' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'totalUsers' : IDL.Nat,
  'activeSessionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addOptionImageToQuestion' : IDL.Func(
      [IDL.Nat, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
  'addQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Option),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        TestType,
      ],
      [IDL.Nat],
      [],
    ),
  'addQuestionsWithClassLevel' : IDL.Func(
      [IDL.Vec(Question), TestType],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'cleanupStaleSessions' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createTestConfig' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        TestType,
        IDL.Nat,
        IDL.Nat,
        IDL.Record({
          'incorrectPenalty' : IDL.Float64,
          'correctMarks' : IDL.Float64,
        }),
        IDL.Vec(IDL.Nat),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(SectionType),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteSuggestion' : IDL.Func([IDL.Nat], [], []),
  'deleteTestConfig' : IDL.Func([IDL.Nat], [], []),
  'filterQuestions' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(TestType),
      ],
      [IDL.Vec(GalleryQuestionPreview)],
      ['query'],
    ),
  'getActiveNonBlockedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getActivePublishedTestConfigs' : IDL.Func(
      [],
      [IDL.Vec(TestConfig)],
      ['query'],
    ),
  'getActiveSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getActiveSessions' : IDL.Func([], [IDL.Vec(ActiveSession)], ['query']),
  'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getAllQuestionsWithImages' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllSuggestions' : IDL.Func([], [SuggestionsResponse], ['query']),
  'getAllTestConfigs' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
  'getAllTestsWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
      ['query'],
    ),
  'getAllUniqueChaptersForSubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllUsersWithTestAttempts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(TestAttempt)))],
      ['query'],
    ),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComment' : IDL.Func([IDL.Nat], [Comment], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFilteredQuestionsCount' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(TestType),
      ],
      [IDL.Nat],
      ['query'],
    ),
  'getLeaderboardByTest' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getOrderedTestConfigs' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
  'getOverallLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(OverallLeaderboardEntry)],
      ['query'],
    ),
  'getPublishedTests' : IDL.Func(
      [],
      [
        IDL.Record({
          'publishedTests' : IDL.Vec(TestConfig),
          'liveCount' : IDL.Nat,
          'scheduledCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestionByTestConfig' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'questions' : IDL.Vec(SanitizedQuestion),
          'testConfig' : TestConfig,
        }),
      ],
      ['query'],
    ),
  'getQuestionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuestionPreview' : IDL.Func(
      [IDL.Nat],
      [GalleryQuestionPreview],
      ['query'],
    ),
  'getQuestionWithAnswersByTestConfig' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'questions' : IDL.Vec(Question),
          'testConfig' : TestConfig,
        }),
      ],
      ['query'],
    ),
  'getQuestionsByChapter' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByIds' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(GalleryQuestionPreview)],
      ['query'],
    ),
  'getQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsForChapter' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsForGallery' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(TestType),
        IDL.Nat,
        IDL.Nat,
      ],
      [
        IDL.Record({
          'totalCount' : IDL.Nat,
          'questions' : IDL.Vec(GalleryQuestionPreview),
          'pageCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getStoppedTestConfigs' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
  'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
  'getTestConfig' : IDL.Func([IDL.Nat], [TestConfig], ['query']),
  'getTestConfigCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTestConfigOrder' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getTestConfigsInOrder' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
  'getTestConfigsWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
      ['query'],
    ),
  'getTestStatus' : IDL.Func([IDL.Nat], [TestStatus], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerBlocked' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'publishTestConfig' : IDL.Func([IDL.Nat], [], []),
  'removeOptionImageFromQuestion' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'reorderTestConfigs' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleTestConfig' : IDL.Func([IDL.Nat, Time, Time], [], []),
  'setQuestionClassLevel' : IDL.Func([IDL.Nat, TestType], [], []),
  'setYouTubeVerified' : IDL.Func([], [], []),
  'setYouTubeVerifiedForUser' : IDL.Func([IDL.Principal], [], []),
  'startTestSession' : IDL.Func([IDL.Nat], [], []),
  'stopTestConfig' : IDL.Func([IDL.Nat], [], []),
  'submitSuggestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitTestAttempt' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Float64],
      [],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unpublishTestConfig' : IDL.Func([IDL.Nat], [], []),
  'updateCallerMobileNumber' : IDL.Func([IDL.Text], [], []),
  'updateQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'subject' : IDL.Text,
          'difficulty' : IDL.Text,
          'explanation' : IDL.Opt(IDL.Text),
          'correctAnswer' : IDL.Nat,
          'questionText' : IDL.Text,
          'classLevel' : TestType,
          'image' : IDL.Opt(ExternalBlob),
          'chapter' : IDL.Text,
          'options' : IDL.Vec(Option),
        }),
      ],
      [],
      [],
    ),
  'updateSessionActivity' : IDL.Func([IDL.Nat], [], []),
  'updateTestConfig' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'startTime' : IDL.Opt(Time),
          'subject' : IDL.Text,
          'endTime' : IDL.Opt(Time),
          'sectionType' : IDL.Opt(SectionType),
          'name' : IDL.Text,
          'testType' : TestType,
          'totalQuestions' : IDL.Nat,
          'durationMinutes' : IDL.Nat,
          'chapters' : IDL.Vec(IDL.Text),
          'markingScheme' : IDL.Record({
            'incorrectPenalty' : IDL.Float64,
            'correctMarks' : IDL.Float64,
          }),
          'questions' : IDL.Vec(IDL.Nat),
        }),
      ],
      [],
      [],
    ),
  'uploadQuestionImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Option = IDL.Record({
    'text' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const TestType = IDL.Variant({
    'class11' : IDL.Null,
    'class12' : IDL.Null,
    'completeSyllabus' : IDL.Null,
  });
  const Time = IDL.Int;
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'updatedAt' : IDL.Opt(Time),
    'classLevel' : TestType,
    'image' : IDL.Opt(ExternalBlob),
    'chapter' : IDL.Text,
    'options' : IDL.Vec(Option),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SectionType = IDL.Variant({
    'full' : IDL.Null,
    'physicsChemistry' : IDL.Null,
    'mathematics' : IDL.Null,
  });
  const GalleryQuestionPreview = IDL.Record({
    'id' : IDL.Nat,
    'previewImage' : IDL.Opt(ExternalBlob),
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'hasImage' : IDL.Bool,
    'snippet' : IDL.Text,
    'questionText' : IDL.Text,
    'chapter' : IDL.Text,
    'options' : IDL.Vec(Option),
  });
  const TestAttempt = IDL.Record({
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'submittedAt' : Time,
    'score' : IDL.Float64,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'createdAt' : Time,
    'youtubeVerificationTimestamp' : IDL.Opt(Time),
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'isYouTubeVerified' : IDL.Bool,
    'lastLogin' : Time,
    'testAttempts' : IDL.Vec(TestAttempt),
    'blockTimestamp' : IDL.Opt(Time),
  });
  const TestConfig = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Opt(Time),
    'isPublished' : IDL.Bool,
    'subject' : IDL.Text,
    'endTime' : IDL.Opt(Time),
    'sectionType' : IDL.Opt(SectionType),
    'isStopped' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'testType' : TestType,
    'updatedAt' : IDL.Opt(Time),
    'totalQuestions' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'chapters' : IDL.Vec(IDL.Text),
    'markingScheme' : IDL.Record({
      'incorrectPenalty' : IDL.Float64,
      'correctMarks' : IDL.Float64,
    }),
    'questions' : IDL.Vec(IDL.Nat),
  });
  const ActiveSession = IDL.Record({
    'startTime' : Time,
    'userId' : IDL.Principal,
    'lastActivity' : Time,
    'testId' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'text' : IDL.Text,
    'timestamp' : Time,
    'questionId' : IDL.Nat,
  });
  const Suggestion = IDL.Record({
    'id' : IDL.Nat,
    'feedback' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const SuggestionsResponse = IDL.Record({
    'suggestions' : IDL.Vec(Suggestion),
    'count' : IDL.Nat,
  });
  const TestStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'ended' : IDL.Null,
    'finished' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'rank' : IDL.Nat,
    'submittedAt' : Time,
    'score' : IDL.Float64,
    'userProfile' : UserProfile,
  });
  const OverallLeaderboardEntry = IDL.Record({
    'rank' : IDL.Nat,
    'totalAttempts' : IDL.Nat,
    'userProfile' : UserProfile,
    'averageScore' : IDL.Float64,
  });
  const SanitizedQuestion = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'questionText' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'chapter' : IDL.Text,
    'options' : IDL.Vec(Option),
  });
  const SystemMetrics = IDL.Record({
    'totalTests' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'totalUsers' : IDL.Nat,
    'activeSessionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addOptionImageToQuestion' : IDL.Func(
        [IDL.Nat, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
    'addQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Option),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          TestType,
        ],
        [IDL.Nat],
        [],
      ),
    'addQuestionsWithClassLevel' : IDL.Func(
        [IDL.Vec(Question), TestType],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'cleanupStaleSessions' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createTestConfig' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          TestType,
          IDL.Nat,
          IDL.Nat,
          IDL.Record({
            'incorrectPenalty' : IDL.Float64,
            'correctMarks' : IDL.Float64,
          }),
          IDL.Vec(IDL.Nat),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(SectionType),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteSuggestion' : IDL.Func([IDL.Nat], [], []),
    'deleteTestConfig' : IDL.Func([IDL.Nat], [], []),
    'filterQuestions' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(TestType),
        ],
        [IDL.Vec(GalleryQuestionPreview)],
        ['query'],
      ),
    'getActiveNonBlockedUsers' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getActivePublishedTestConfigs' : IDL.Func(
        [],
        [IDL.Vec(TestConfig)],
        ['query'],
      ),
    'getActiveSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getActiveSessions' : IDL.Func([], [IDL.Vec(ActiveSession)], ['query']),
    'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getAllQuestionsWithImages' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllSuggestions' : IDL.Func([], [SuggestionsResponse], ['query']),
    'getAllTestConfigs' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
    'getAllTestsWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
        ['query'],
      ),
    'getAllUniqueChaptersForSubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllUsersWithTestAttempts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserProfile, IDL.Vec(TestAttempt)))],
        ['query'],
      ),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComment' : IDL.Func([IDL.Nat], [Comment], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFilteredQuestionsCount' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(TestType),
        ],
        [IDL.Nat],
        ['query'],
      ),
    'getLeaderboardByTest' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getOrderedTestConfigs' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
    'getOverallLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(OverallLeaderboardEntry)],
        ['query'],
      ),
    'getPublishedTests' : IDL.Func(
        [],
        [
          IDL.Record({
            'publishedTests' : IDL.Vec(TestConfig),
            'liveCount' : IDL.Nat,
            'scheduledCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestionByTestConfig' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'questions' : IDL.Vec(SanitizedQuestion),
            'testConfig' : TestConfig,
          }),
        ],
        ['query'],
      ),
    'getQuestionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuestionPreview' : IDL.Func(
        [IDL.Nat],
        [GalleryQuestionPreview],
        ['query'],
      ),
    'getQuestionWithAnswersByTestConfig' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'questions' : IDL.Vec(Question),
            'testConfig' : TestConfig,
          }),
        ],
        ['query'],
      ),
    'getQuestionsByChapter' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByIds' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(GalleryQuestionPreview)],
        ['query'],
      ),
    'getQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsForChapter' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsForGallery' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(TestType),
          IDL.Nat,
          IDL.Nat,
        ],
        [
          IDL.Record({
            'totalCount' : IDL.Nat,
            'questions' : IDL.Vec(GalleryQuestionPreview),
            'pageCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getStoppedTestConfigs' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
    'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
    'getTestConfig' : IDL.Func([IDL.Nat], [TestConfig], ['query']),
    'getTestConfigCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTestConfigOrder' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getTestConfigsInOrder' : IDL.Func([], [IDL.Vec(TestConfig)], ['query']),
    'getTestConfigsWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
        ['query'],
      ),
    'getTestStatus' : IDL.Func([IDL.Nat], [TestStatus], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerBlocked' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'publishTestConfig' : IDL.Func([IDL.Nat], [], []),
    'removeOptionImageFromQuestion' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'reorderTestConfigs' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleTestConfig' : IDL.Func([IDL.Nat, Time, Time], [], []),
    'setQuestionClassLevel' : IDL.Func([IDL.Nat, TestType], [], []),
    'setYouTubeVerified' : IDL.Func([], [], []),
    'setYouTubeVerifiedForUser' : IDL.Func([IDL.Principal], [], []),
    'startTestSession' : IDL.Func([IDL.Nat], [], []),
    'stopTestConfig' : IDL.Func([IDL.Nat], [], []),
    'submitSuggestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitTestAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Float64],
        [],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unpublishTestConfig' : IDL.Func([IDL.Nat], [], []),
    'updateCallerMobileNumber' : IDL.Func([IDL.Text], [], []),
    'updateQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'subject' : IDL.Text,
            'difficulty' : IDL.Text,
            'explanation' : IDL.Opt(IDL.Text),
            'correctAnswer' : IDL.Nat,
            'questionText' : IDL.Text,
            'classLevel' : TestType,
            'image' : IDL.Opt(ExternalBlob),
            'chapter' : IDL.Text,
            'options' : IDL.Vec(Option),
          }),
        ],
        [],
        [],
      ),
    'updateSessionActivity' : IDL.Func([IDL.Nat], [], []),
    'updateTestConfig' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'startTime' : IDL.Opt(Time),
            'subject' : IDL.Text,
            'endTime' : IDL.Opt(Time),
            'sectionType' : IDL.Opt(SectionType),
            'name' : IDL.Text,
            'testType' : TestType,
            'totalQuestions' : IDL.Nat,
            'durationMinutes' : IDL.Nat,
            'chapters' : IDL.Vec(IDL.Text),
            'markingScheme' : IDL.Record({
              'incorrectPenalty' : IDL.Float64,
              'correctMarks' : IDL.Float64,
            }),
            'questions' : IDL.Vec(IDL.Nat),
          }),
        ],
        [],
        [],
      ),
    'uploadQuestionImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };