/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Option = IDL.Record({
  'text' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const TestType = IDL.Variant({
  'class11' : IDL.Null,
  'class12' : IDL.Null,
  'completeSyllabus' : IDL.Null,
});
export const Time = IDL.Int;
export const SectionType = IDL.Variant({
  'full' : IDL.Null,
  'physicsChemistry' : IDL.Null,
  'mathematics' : IDL.Null,
});
export const TestConfig = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Opt(Time),
  'isPublished' : IDL.Bool,
  'subject' : IDL.Text,
  'endTime' : IDL.Opt(Time),
  'sectionType' : IDL.Opt(SectionType),
  'isStopped' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'testType' : TestType,
  'updatedAt' : IDL.Opt(Time),
  'totalQuestions' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'chapters' : IDL.Vec(IDL.Text),
  'markingScheme' : IDL.Record({
    'incorrectPenalty' : IDL.Nat,
    'correctMarks' : IDL.Nat,
    'penaltyOption' : IDL.Opt(IDL.Text),
  }),
  'questions' : IDL.Vec(IDL.Nat),
});
export const TestStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'ended' : IDL.Null,
  'finished' : IDL.Null,
});
export const TestAttempt = IDL.Record({
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'submittedAt' : Time,
  'score' : IDL.Nat,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'createdAt' : Time,
  'youtubeVerificationTimestamp' : IDL.Opt(Time),
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'isYouTubeVerified' : IDL.Bool,
  'lastLogin' : Time,
  'testAttempts' : IDL.Vec(TestAttempt),
  'blockTimestamp' : IDL.Opt(Time),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'updatedAt' : IDL.Opt(Time),
  'classLevel' : TestType,
  'image' : IDL.Opt(ExternalBlob),
  'chapter' : IDL.Text,
  'options' : IDL.Vec(Option),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'text' : IDL.Text,
  'timestamp' : Time,
  'questionId' : IDL.Nat,
});
export const Suggestion = IDL.Record({
  'id' : IDL.Nat,
  'feedback' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const SuggestionsResponse = IDL.Record({
  'suggestions' : IDL.Vec(Suggestion),
  'count' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachOptionImage' : IDL.Func([IDL.Nat, IDL.Nat, ExternalBlob], [], []),
  'attachQuestionImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'createQuestion' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Option),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        TestType,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteExpiredUnpublishedTests' : IDL.Func([], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteSuggestion' : IDL.Func([IDL.Nat], [], []),
  'getAllTestConfigsWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentlyLiveTestsWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
      ['query'],
    ),
  'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCommentsForQuestion' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'listQuestions' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'listQuestionsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'listSuggestions' : IDL.Func([], [SuggestionsResponse], ['query']),
  'postComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [UserProfile], []),
  'setYouTubeVerified' : IDL.Func([], [], []),
  'submitSuggestion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Option),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        TestType,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Option = IDL.Record({
    'text' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const TestType = IDL.Variant({
    'class11' : IDL.Null,
    'class12' : IDL.Null,
    'completeSyllabus' : IDL.Null,
  });
  const Time = IDL.Int;
  const SectionType = IDL.Variant({
    'full' : IDL.Null,
    'physicsChemistry' : IDL.Null,
    'mathematics' : IDL.Null,
  });
  const TestConfig = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Opt(Time),
    'isPublished' : IDL.Bool,
    'subject' : IDL.Text,
    'endTime' : IDL.Opt(Time),
    'sectionType' : IDL.Opt(SectionType),
    'isStopped' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'testType' : TestType,
    'updatedAt' : IDL.Opt(Time),
    'totalQuestions' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'chapters' : IDL.Vec(IDL.Text),
    'markingScheme' : IDL.Record({
      'incorrectPenalty' : IDL.Nat,
      'correctMarks' : IDL.Nat,
      'penaltyOption' : IDL.Opt(IDL.Text),
    }),
    'questions' : IDL.Vec(IDL.Nat),
  });
  const TestStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'ended' : IDL.Null,
    'finished' : IDL.Null,
  });
  const TestAttempt = IDL.Record({
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'submittedAt' : Time,
    'score' : IDL.Nat,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'createdAt' : Time,
    'youtubeVerificationTimestamp' : IDL.Opt(Time),
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'isYouTubeVerified' : IDL.Bool,
    'lastLogin' : Time,
    'testAttempts' : IDL.Vec(TestAttempt),
    'blockTimestamp' : IDL.Opt(Time),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'updatedAt' : IDL.Opt(Time),
    'classLevel' : TestType,
    'image' : IDL.Opt(ExternalBlob),
    'chapter' : IDL.Text,
    'options' : IDL.Vec(Option),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'text' : IDL.Text,
    'timestamp' : Time,
    'questionId' : IDL.Nat,
  });
  const Suggestion = IDL.Record({
    'id' : IDL.Nat,
    'feedback' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const SuggestionsResponse = IDL.Record({
    'suggestions' : IDL.Vec(Suggestion),
    'count' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachOptionImage' : IDL.Func([IDL.Nat, IDL.Nat, ExternalBlob], [], []),
    'attachQuestionImage' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'createQuestion' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Option),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          TestType,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteExpiredUnpublishedTests' : IDL.Func([], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteSuggestion' : IDL.Func([IDL.Nat], [], []),
    'getAllTestConfigsWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentlyLiveTestsWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TestConfig, TestStatus))],
        ['query'],
      ),
    'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCommentsForQuestion' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'listQuestions' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'listQuestionsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'listSuggestions' : IDL.Func([], [SuggestionsResponse], ['query']),
    'postComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [UserProfile], []),
    'setYouTubeVerified' : IDL.Func([], [], []),
    'submitSuggestion' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Option),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          TestType,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };