/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveSession {
  'startTime' : Time,
  'userId' : Principal,
  'lastActivity' : Time,
  'testId' : bigint,
}
export interface Comment {
  'id' : bigint,
  'userId' : Principal,
  'text' : string,
  'timestamp' : Time,
  'questionId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface GalleryQuestionPreview {
  'id' : bigint,
  'previewImage' : [] | [ExternalBlob],
  'subject' : string,
  'difficulty' : string,
  'hasImage' : boolean,
  'snippet' : string,
  'questionText' : string,
  'chapter' : string,
  'options' : Array<Option>,
}
export interface LeaderboardEntry {
  'rank' : bigint,
  'submittedAt' : Time,
  'score' : number,
  'userProfile' : UserProfile,
}
export interface Option { 'text' : string, 'image' : [] | [ExternalBlob] }
export interface OverallLeaderboardEntry {
  'rank' : bigint,
  'totalAttempts' : bigint,
  'userProfile' : UserProfile,
  'averageScore' : number,
}
export interface Question {
  'id' : bigint,
  'subject' : string,
  'difficulty' : string,
  'explanation' : [] | [string],
  'createdAt' : Time,
  'createdBy' : Principal,
  'correctAnswer' : bigint,
  'questionText' : string,
  'updatedAt' : [] | [Time],
  'classLevel' : TestType,
  'image' : [] | [ExternalBlob],
  'chapter' : string,
  'options' : Array<Option>,
}
export interface SanitizedQuestion {
  'id' : bigint,
  'subject' : string,
  'difficulty' : string,
  'questionText' : string,
  'image' : [] | [ExternalBlob],
  'chapter' : string,
  'options' : Array<Option>,
}
export type SectionType = { 'full' : null } |
  { 'physicsChemistry' : null } |
  { 'mathematics' : null };
export interface Suggestion {
  'id' : bigint,
  'feedback' : string,
  'author' : string,
  'timestamp' : Time,
}
export interface SuggestionsResponse {
  'suggestions' : Array<Suggestion>,
  'count' : bigint,
}
export interface SystemMetrics {
  'totalTests' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'totalUsers' : bigint,
  'activeSessionCount' : bigint,
}
export interface TestAttempt {
  'userId' : Principal,
  'answers' : Array<bigint>,
  'submittedAt' : Time,
  'score' : number,
  'timeTaken' : bigint,
  'testId' : bigint,
}
export interface TestConfig {
  'id' : bigint,
  'startTime' : [] | [Time],
  'isPublished' : boolean,
  'subject' : string,
  'endTime' : [] | [Time],
  'sectionType' : [] | [SectionType],
  'isStopped' : boolean,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'testType' : TestType,
  'updatedAt' : [] | [Time],
  'totalQuestions' : bigint,
  'durationMinutes' : bigint,
  'chapters' : Array<string>,
  'markingScheme' : { 'incorrectPenalty' : number, 'correctMarks' : number },
  'questions' : Array<bigint>,
}
export type TestStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'ended' : null } |
  { 'finished' : null };
export type TestType = { 'class11' : null } |
  { 'class12' : null } |
  { 'completeSyllabus' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'isBlocked' : boolean,
  'createdAt' : Time,
  'youtubeVerificationTimestamp' : [] | [Time],
  'fullName' : string,
  'mobileNumber' : string,
  'email' : string,
  'isYouTubeVerified' : boolean,
  'lastLogin' : Time,
  'testAttempts' : Array<TestAttempt>,
  'blockTimestamp' : [] | [Time],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'addOptionImageToQuestion' : ActorMethod<
    [bigint, bigint, ExternalBlob],
    undefined
  >,
  'addQuestion' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<Option>,
      bigint,
      [] | [string],
      [] | [ExternalBlob],
      TestType,
    ],
    bigint
  >,
  'addQuestionsWithClassLevel' : ActorMethod<
    [Array<Question>, TestType],
    Array<bigint>
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'cleanupStaleSessions' : ActorMethod<[bigint], bigint>,
  'createTestConfig' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      TestType,
      bigint,
      bigint,
      { 'incorrectPenalty' : number, 'correctMarks' : number },
      Array<bigint>,
      [] | [Time],
      [] | [Time],
      [] | [SectionType],
    ],
    bigint
  >,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteSuggestion' : ActorMethod<[bigint], undefined>,
  'deleteTestConfig' : ActorMethod<[bigint], undefined>,
  'filterQuestions' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [TestType]],
    Array<GalleryQuestionPreview>
  >,
  'getActiveNonBlockedUsers' : ActorMethod<[], Array<UserProfile>>,
  'getActivePublishedTestConfigs' : ActorMethod<[], Array<TestConfig>>,
  'getActiveSessionCount' : ActorMethod<[], bigint>,
  'getActiveSessions' : ActorMethod<[], Array<ActiveSession>>,
  'getAllComments' : ActorMethod<[], Array<Comment>>,
  'getAllQuestionsWithImages' : ActorMethod<[], Array<Question>>,
  'getAllSuggestions' : ActorMethod<[], SuggestionsResponse>,
  'getAllTestConfigs' : ActorMethod<[], Array<TestConfig>>,
  'getAllTestsWithStatus' : ActorMethod<[], Array<[TestConfig, TestStatus]>>,
  'getAllUniqueChaptersForSubject' : ActorMethod<[string], Array<string>>,
  'getAllUsersWithTestAttempts' : ActorMethod<
    [],
    Array<[UserProfile, Array<TestAttempt>]>
  >,
  'getBlockedUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComment' : ActorMethod<[bigint], Comment>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getFilteredQuestionsCount' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [TestType]],
    bigint
  >,
  'getLeaderboardByTest' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getOrderedTestConfigs' : ActorMethod<[], Array<TestConfig>>,
  'getOverallLeaderboard' : ActorMethod<[], Array<OverallLeaderboardEntry>>,
  'getPublishedTests' : ActorMethod<
    [],
    {
      'publishedTests' : Array<TestConfig>,
      'liveCount' : bigint,
      'scheduledCount' : bigint,
    }
  >,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getQuestionByTestConfig' : ActorMethod<
    [bigint],
    { 'questions' : Array<SanitizedQuestion>, 'testConfig' : TestConfig }
  >,
  'getQuestionCount' : ActorMethod<[], bigint>,
  'getQuestionPreview' : ActorMethod<[bigint], GalleryQuestionPreview>,
  'getQuestionWithAnswersByTestConfig' : ActorMethod<
    [bigint],
    { 'questions' : Array<Question>, 'testConfig' : TestConfig }
  >,
  'getQuestionsByChapter' : ActorMethod<[string, string], Array<Question>>,
  'getQuestionsByIds' : ActorMethod<
    [Array<bigint>],
    Array<GalleryQuestionPreview>
  >,
  'getQuestionsBySubject' : ActorMethod<[string], Array<Question>>,
  'getQuestionsForChapter' : ActorMethod<[string, string], Array<Question>>,
  'getQuestionsForGallery' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [TestType],
      bigint,
      bigint,
    ],
    {
      'totalCount' : bigint,
      'questions' : Array<GalleryQuestionPreview>,
      'pageCount' : bigint,
    }
  >,
  'getStoppedTestConfigs' : ActorMethod<[], Array<TestConfig>>,
  'getSystemMetrics' : ActorMethod<[], SystemMetrics>,
  'getTestConfig' : ActorMethod<[bigint], TestConfig>,
  'getTestConfigCount' : ActorMethod<[], bigint>,
  'getTestConfigOrder' : ActorMethod<[], Array<bigint>>,
  'getTestConfigsInOrder' : ActorMethod<[], Array<TestConfig>>,
  'getTestConfigsWithStatus' : ActorMethod<[], Array<[TestConfig, TestStatus]>>,
  'getTestStatus' : ActorMethod<[bigint], TestStatus>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerBlocked' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'publishTestConfig' : ActorMethod<[bigint], undefined>,
  'removeOptionImageFromQuestion' : ActorMethod<[bigint, bigint], undefined>,
  'reorderTestConfigs' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleTestConfig' : ActorMethod<[bigint, Time, Time], undefined>,
  'setQuestionClassLevel' : ActorMethod<[bigint, TestType], undefined>,
  'setYouTubeVerified' : ActorMethod<[], undefined>,
  'setYouTubeVerifiedForUser' : ActorMethod<[Principal], undefined>,
  'startTestSession' : ActorMethod<[bigint], undefined>,
  'stopTestConfig' : ActorMethod<[bigint], undefined>,
  'submitSuggestion' : ActorMethod<[string, string], undefined>,
  'submitTestAttempt' : ActorMethod<[bigint, Array<bigint>], number>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unpublishTestConfig' : ActorMethod<[bigint], undefined>,
  'updateCallerMobileNumber' : ActorMethod<[string], undefined>,
  'updateQuestion' : ActorMethod<
    [
      bigint,
      {
        'subject' : string,
        'difficulty' : string,
        'explanation' : [] | [string],
        'correctAnswer' : bigint,
        'questionText' : string,
        'classLevel' : TestType,
        'image' : [] | [ExternalBlob],
        'chapter' : string,
        'options' : Array<Option>,
      },
    ],
    undefined
  >,
  'updateSessionActivity' : ActorMethod<[bigint], undefined>,
  'updateTestConfig' : ActorMethod<
    [
      bigint,
      {
        'startTime' : [] | [Time],
        'subject' : string,
        'endTime' : [] | [Time],
        'sectionType' : [] | [SectionType],
        'name' : string,
        'testType' : TestType,
        'totalQuestions' : bigint,
        'durationMinutes' : bigint,
        'chapters' : Array<string>,
        'markingScheme' : {
          'incorrectPenalty' : number,
          'correctMarks' : number,
        },
        'questions' : Array<bigint>,
      },
    ],
    undefined
  >,
  'uploadQuestionImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];